POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Teste 2"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/d19021a8-7bb3-44f8-a979-a7b65e0fbb2a