POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Java"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/47ebaeb0-5833-4790-a51f-a9df600508e6